---
apiVersion: gateway.mulesoft.com/v1alpha1
kind: Extension
metadata:
  labels:
    title: shkthree
    category: Custom
    pdk.mulesoft.com/pdk-cli-version: 1.0.1
  name: shkthree-v1-0
spec:
  extends:
    - name: extension-definition
      namespace: default
  properties:
    stringProperty:
      type: string
      default: some value
  required:
    - stringProperty
